---
name: "Build and test"

on:
  push:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build
      run: echo "Building app..."
    - name: Unit test
      run: echo "Running tests..."