---
name: "tagged-release"

on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create git tag
        run: git tag $(yq '.version' ./version.yml)
      - name: Push git tag
        run: git push origin $(yq '.version' ./version.yml)
