---
name: "tagged-release"

on:
  push:
    branches: [ "main" ]
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Create git tag
        run: git tag testerino
      - name: Push git tag
        run: git push origin testerino
      - name: Set Dist Version
        run: echo "VERSION_NUMBER=$(yq '.version' ./version.yml)" >> $GITHUB_ENV
      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            const {DIST_VERSION} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${DIST_VERSION}`,
                sha: context.sha
            })
