---
name: "tagged-release"

on:
  push:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fuck
      run: yq '.version' version.yml
    - name: Version
      run: VERSION_NUMBER=$(xddd)
    - name: Show version!
      run: echo $VERSION_NUMBER